# Generated by Django 4.2.7 on 2023-11-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift', models.CharField(choices=[('Bench', 'Bench Press'), ('Squat', 'Squat'), ('Deadlift', 'Deadlift')], max_length=10)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
