# Generated by Django 4.2.7 on 2023-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0002_fitness_delete_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='date',
            field=models.DateField(default='26-11-2023'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='lift',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='fitness',
            unique_together={('user_name', 'lift')},
        ),
    ]
