# Generated by Django 4.2.7 on 2023-11-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0003_alter_fitness_date_alter_fitness_lift_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fitness',
            unique_together={('user_name', 'date', 'lift')},
        ),
    ]
