# Generated by Django 4.2.7 on 2023-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0004_alter_fitness_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fitness',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fitness',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitness',
            name='date',
            field=models.DateField(default='02-12-2023'),
        ),
        migrations.AlterUniqueTogether(
            name='fitness',
            unique_together={('user_id', 'date', 'lift')},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('user_name',)},
            },
        ),
        migrations.RemoveField(
            model_name='fitness',
            name='user_name',
        ),
    ]
