# Generated by Django 4.2.7 on 2023-12-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0005_alter_fitness_unique_together_fitness_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterUniqueTogether(
            name='fitness',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fitness',
            name='user_id',
        ),
    ]
