# Generated by Django 4.2.7 on 2023-12-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0006_delete_user_alter_fitness_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='user_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fitness',
            unique_together={('user_name', 'date', 'lift')},
        ),
    ]
