# Generated by Django 4.2.7 on 2023-12-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0007_fitness_user_name_alter_fitness_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('calorie', models.IntegerField(max_length=3)),
                ('protein', models.IntegerField(max_length=3)),
                ('carbs', models.IntegerField(max_length=3)),
                ('fats', models.IntegerField(max_length=3)),
            ],
            options={
                'unique_together': {('user_name', 'type')},
            },
        ),
    ]
