# Generated by Django 4.2.7 on 2023-12-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0008_calorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='calorie',
            unique_together={('user', 'type')},
        ),
    ]
