# Generated by Django 4.2.7 on 2023-12-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0009_rename_user_name_calorie_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AlterUniqueTogether(
            name='calorie',
            unique_together={('user_name', 'type')},
        ),
    ]
