# Generated by Django 4.2.7 on 2024-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0010_rename_user_calorie_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='date',
            field=models.DateField(default='23-02-2024'),
        ),
    ]
