# Generated by Django 4.2.7 on 2024-03-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitness', '0011_alter_fitness_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='date',
            field=models.DateField(default='15-03-2024'),
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('date', models.DateField(default='15-03-2024')),
                ('start', models.IntegerField(max_length=3)),
                ('goal', models.IntegerField(max_length=3)),
                ('last', models.IntegerField(max_length=3)),
                ('current', models.IntegerField(max_length=3)),
            ],
            options={
                'unique_together': {('user_name',)},
            },
        ),
    ]
